<?php require_once __DIR__ . '/../includes/bootstrap.php';
$notices = $pdo->query('SELECT * FROM notices ORDER BY published_at DESC LIMIT 5')->fetchAll();
$testimonials = $pdo->query('SELECT * FROM testimonials ORDER BY id DESC LIMIT 5')->fetchAll();
$gallery = $pdo->query('SELECT * FROM gallery ORDER BY id DESC LIMIT 8')->fetchAll();
include __DIR__ . '/../includes/header.php';
?>
<nav class="topnav"><div class="container topnav-inner"><div class="brand"><i class="fa-solid fa-school"></i> NovaSchool</div><div class="nav-links"><a href="/public/about.php">About</a><a href="/public/admissions.php">Admissions</a><a href="/public/gallery.php">Gallery</a><a href="/public/notices.php">Notices</a><a href="/public/contact.php">Contact</a><a class="btn" href="/auth/login.php">Login Portal</a></div></div></nav>
<header class="hero"><div class="container hero-grid"><div><h1 class="gradient-text">Ultra-Premium School ERP + Website</h1><p>Digital-first campus platform for admissions, academics, communication, and payments.</p><div style="display:flex;gap:.7rem"><a class="btn" href="/public/admissions.php">Apply Now</a><a class="btn secondary" href="/auth/login.php">Login</a></div></div><div class="glass card"><h3>Admission Open 2026-27</h3><p>Smart onboarding, online forms, and real-time status tracking for guardians.</p></div></div></header>
<section class="section"><div class="container"><h2>Why Choose Us</h2><div class="card-grid"><?php foreach ([['fa-shield-halved','Secure & Compliant'],['fa-chart-line','Academic Insights'],['fa-bell','Live Notifications'],['fa-credit-card','PayU Payments']] as $item): ?><article class="glass card"><i class="fa-solid <?= $item[0] ?>"></i><h4><?= e($item[1]) ?></h4></article><?php endforeach; ?></div></div></section>
<section class="section"><div class="container"><h2>Classes 1-12</h2><div class="card-grid"><?php for($i=1;$i<=12;$i++): ?><div class="glass card">Class <?= $i ?></div><?php endfor; ?></div></div></section>
<section class="section"><div class="container"><h2>Notice Board</h2><div class="glass card"><?php foreach($notices as $notice): ?><div class="notice-item"><span><?= e($notice['title']) ?></span><small><?= e($notice['published_at']) ?></small></div><?php endforeach; ?></div></div></section>
<section class="section"><div class="container"><h2>Gallery</h2><div class="card-grid"><?php foreach($gallery as $g): ?><div class="glass card"><img src="<?= e($g['image_path'] ?: 'https://picsum.photos/400/250?random=' . $g['id']) ?>" style="width:100%;border-radius:14px"><p><?= e($g['title']) ?></p></div><?php endforeach; ?></div></div></section>
<section class="section"><div class="container"><h2>Testimonials</h2><div class="card-grid"><?php foreach($testimonials as $t): ?><div class="glass card"><p>“<?= e($t['quote']) ?>”</p><strong><?= e($t['name']) ?></strong><small><?= e($t['role']) ?></small></div><?php endforeach; ?></div></div></section>
<footer class="footer"><div class="container footer-grid"><div><h4>NovaSchool</h4><p>Future-ready campus management.</p></div><div><h4>Quick Links</h4><p><a href="/public/about.php">About</a> · <a href="/public/contact.php">Contact</a></p></div><div><h4>Portal</h4><p><a href="/auth/login.php?role=admin">Admin</a> · <a href="/auth/login.php?role=student">Student</a> · <a href="/auth/login.php?role=teacher">Teacher</a> · <a href="/auth/login.php?role=parent">Parent</a></p></div></div></footer>
<?php include __DIR__ . '/../includes/footer.php'; ?>
